services:
    # Django
    django_auth:
        container_name: django_auth
        build: .
        command: uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --reload
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on:
            - auth_redis
            - auth_db
    
    # Redis
    auth_redis:
        image: redis
        container_name: auth_redis
        ports:
            - 6379:6380
    
    # Database
    auth_db:
        image: postgres
        container_name: auth_db
        restart: always
        environment:
            POSTGRES_DB: django_db
            POSTGRES_USER: django
            POSTGRES_PASSWORD: postgres
        ports:
            - 5434:5434
        volumes:
            - .dbdata:/var/lib/postgresql