# Generated by Django 4.2.16 on 2025-09-23 19:08

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('biography', ckeditor.fields.RichTextField(blank=True, default='')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('website', models.URLField(blank=True, default='')),
                ('instagram', models.URLField(blank=True, default='')),
                ('facebook', models.URLField(blank=True, default='')),
                ('threads', models.URLField(blank=True, default='')),
                ('linkedin', models.URLField(blank=True, default='')),
                ('youtube', models.URLField(blank=True, default='')),
                ('tiktok', models.URLField(blank=True, default='')),
                ('github', models.URLField(blank=True, default='')),
                ('gitlab', models.URLField(blank=True, default='')),
                ('banner_picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_banner_picture_of', to='assets.media')),
                ('profile_picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_profile_picture_of', to='assets.media')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'indexes': [models.Index(fields=['birthday'], name='user_profil_birthda_6e3ed4_idx')],
            },
        ),
    ]
