# Generated by Django 4.2.16 on 2025-09-23 19:08

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=256)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(choices=[('image/jpeg', 'JPEG'), ('image/png', 'PNG'), ('image/webp', 'WEBP'), ('image/gif', 'GIF'), ('image/svg+xml', 'SVG'), ('video/mp4', 'MP4'), ('video/webm', 'WEBM'), ('video/quicktime', 'QuickTime (.mov)'), ('audio/mpeg', 'MP3'), ('audio/wav', 'WAV'), ('audio/ogg', 'OGG'), ('application/pdf', 'PDF'), ('text/plain', 'Texto'), ('text/csv', 'CSV'), ('application/json', 'JSON'), ('application/zip', 'ZIP'), ('application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'DOCX'), ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'XLSX'), ('application/octet-stream', 'Binario/Otro')], db_index=True, default='application/octet-stream', max_length=128)),
                ('key', models.CharField(db_index=True, max_length=512, unique=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio')], max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
