# Generated by Django 4.2.16 on 2025-09-23 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['media_type'], name='assets_medi_media_t_2fe438_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['created_at'], name='assets_medi_created_4eaff5_idx'),
        ),
    ]
