# Generated by Django 4.2.16 on 2025-08-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_useraccount_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='otp_last_counter',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
